name: Alphafold to DockerHub

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  IMAGE: catgumag/alphafold

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get current date (for tag)
        id: get_date
        run: echo ::set-output name=DATE::$(date +'%Y%m%d')

      - name: Get version from tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/v}

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.IMAGE_VERSION }}
            ${{ env.IMAGE }}:latest
        env:
          IMAGE_VERSION: ${{ github.ref == 'refs/heads/main' &&
                             format('dev{0}', steps.get_date.outputs.DATE) ||
                             steps.get_version.outputs.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}